version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zoo1
    container_name: zoo1
    restart: unless-stopped
    ports:
      - "2181:2181"
  kafka1:
      image: wurstmeister/kafka
      ports:
            - "9092:9092"
      environment:
            KAFKA_ADVERTISED_HOST_NAME: "34.92.93.183"
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
            KAFKA_CREATE_TOPICS: "test,engine.oms.loadOrder13,stream-out:1:1,"
            KAFKA_DELETE_TOPIC_ENABLE: "true"
      depends_on:
            - zookeeper
      container_name: kafka1      
  kafka2:
      image: wurstmeister/kafka
      ports:
            - "9093:9092"
      environment:
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_ADVERTISED_HOST_NAME: "34.92.93.183"
            KAFKA_ADVERTISED_PORT: 9093
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
            KAFKA_BROKER_ID: 2
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      depends_on:
            - zookeeper
      container_name: kafka2
  kafka3:
      image: wurstmeister/kafka
      ports:
            - "9094:9092"
      environment:
            KAFKA_DELETE_TOPIC_ENABLE: "true"   
            KAFKA_ADVERTISED_HOST_NAME: "34.92.93.183"
            KAFKA_ADVERTISED_PORT: 9094
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
            KAFKA_BROKER_ID: 3
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      depends_on:
            - zookeeper
      container_name: kafka3     
